# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Versions
- group: Credentials

steps:
# - script: |
#     echo install init!!!
#     #curl -sfL https://releases.dagger.io/dagger/install.sh | sh
#     # globally
#     curl -sfL https://releases.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin sh
#     echo install end!!!
#   displayName: 'Dagger install!'
 
# - script: |
#     echo dagger verify!!!
#     dagger version
#     echo docker verify!!!
#     docker version
#   displayName: 'Dagger verify'

- script: |
    echo kube init!!!
    echo -n $(KUBE_CONFIG_DATA) | base64 -d > ~/.kube/config
    echo kube end!!!
  displayName: 'kube init'

- script: |
    echo install init!!!
    cd /usr/local
    curl -L https://dl.dagger.io/dagger-cue/install.sh | sh
    echo install end!!!
  displayName: 'Dagger-cue install!'

- script: |
    echo dagger verify!!!
    dagger-cue version
    echo docker verify!!!
    docker version
  displayName: 'Dagger-cue verify'

- script: |
    echo dagger init!!!
    dagger-cue project init
    dagger-cue project update
  displayName: 'Dagger init'  

- script: |
    echo deploy!!!
    dagger-cue do deploy --log-format plain
  displayName: 'Dagger deploy'




 